### ISSUE TITLE
image for docker compose?

### ISSUE THREAD

**Issue by somedevreally** [pictuga/morss#38]
Hello,

i have existing docker compose, in which i want to add morss as another service, 
is there any image available either on dockerhub/github.?
if i try `git.pictuga.com/pictuga/morss.git` as is obviously it gives error.

**Comment by pictuga** [comment]
No image available at the moment. For now you can use the following in your docker compose file:

```yml
services:
    app:
        build: https://git.pictuga.com/pictuga/morss.git
        ports:
            - '8080:8080'
```

Then run `docker-compose up --build`

Does that work on your side?
