### ISSUE TITLE
Memory leak issues

### ISSUE THREAD

**Issue by JulienSambre** [pictuga/morss#46]
Hi!

I have a big issue with morss : the app act like it have a memory leak : 

![image](https://user-images.githubusercontent.com/14327288/94514111-b0010d00-0220-11eb-8d0c-2834b613fdf3.png)

The only way to handle the problem is to restart the container : not very handy :).

I use the container version of morss, building it from https://git.pictuga.com/pictuga/morss.git , without passing argument (so on gunicorn). I rebuild it yesterday without any improvement.

In order to handle this problem, I tried, without any better, to : 

1. Use a sqlite cache
2. Use a mariadb cache
3. Set some environment variable (MAX_ITEM=20)

I had some problem with morss for connecting to mariadb, but I think it "works" because I see lines in the data tables : 
- I had to remove options of mariadb in order to morss not crashing (data length error at start)
- I have some error showing that connections are not ended correctly, but without error on morss output : "[Warning] Aborted connection 12619 to db: 'XXX' user: 'YYY' host: 'ZZZ' (Got an error reading communication packets)"

I didn't understand well how some environment variables work (MAX_ITEM & LIM_ITEM), maybe I need to use this? 

Thanks for help :).

**Comment by pictuga** [comment]
Well spotted. Since it also affects the mariadb cache, it probably has something to do with `Uniq` (from `feeds.py`) which is preventing the garbage collection from doing its job https://git.pictuga.com/pictuga/morss/src/branch/master/morss/feeds.py#L630

As for MAX_ITEM and LIM_ITEM they are of no use here. The code however lacks an ability to control the cache (which otherwise grows indefinitely)

Todo
[] Refactor Uniq code
[] Add option to cap cache size

**Comment by JulienSambre** [comment]
Hi!

I'm pretty happy to know that I didn't do stupid things :).

I will follow these fix / improvement because I use actively morss despite of that, its features are very nice :).

Thanks for the quick answer!

**Comment by pictuga** [comment]
The cache size thing should be fixed (see https://git.pictuga.com/pictuga/morss#cache-information)

The Uniq code is still not solved

**Comment by JulienSambre** [comment]
Hi!

I've just rebuild the container, removing Mariadb for Sqlite.

I will tell you today if this works now.

**Comment by pictuga** [comment]
You probably want to use some custom value for CACHE_SIZE (default of 10k entries) ;) morss.it has it set at 3k

**Comment by JulienSambre** [comment]
Ok, just changed it.

What kind of cache do you have for morss.it? mysql?

**Comment by pictuga** [comment]
MySQL for performance (and cause the cheap hosting it's running on has nothing else to offer)

**Comment by JulienSambre** [comment]
Ok, I switched back to MySQL.

Thanks for your help and quick answers ;).

**Comment by JulienSambre** [comment]
Hi!

I changed the CACHE_SIZE to 200, but no improvement : the memory continues to go up and up

![image](https://user-images.githubusercontent.com/14327288/94900929-235f8480-0496-11eb-8ce3-a89eb7437d2a.png)

Here is my docker config : have I made a mistake?

```
version: '2.2'

services:

    morss:
      build: https://git.pictuga.com/pictuga/morss.git
      container_name: morss
      mem_limit: 300m
      links:
        - mariadb-morss      
      ports:
        - 'XXX:8080'
      environment:
        CACHE: mysql
        CACHE_SIZE: 200
        MYSQL_USER: XXX
        MYSQL_PWD: XXX
        MYSQL_DB: XXX
        MYSQL_HOST: mariadb-morss        
      cpus: 0.2
      logging:
          driver: "json-file"
          options:
              max-size: 5m
    mariadb-morss:
      image: mariadb:10.5.5
      container_name: mariadb-morss
      environment:
        MYSQL_ROOT_PASSWORD: "XXX"
        MYSQL_DATABASE: XXX
        MYSQL_USER: XXX
        MYSQL_PASSWORD: XXX
      command: --sql_mode=''
      volumes:
        - ./db:/var/lib/mysql
      logging:
          driver: "json-file"
          options:
              max-size: 5m      
```
